### ISSUE TITLE
Add .NETStandard 1.1 or .NETFramework 4.5

### ISSUE THREAD

**Issue by ndrwrbgs** [opentracing-contrib/csharp-decorators#1]
I'd like to consume this but sadly my code base is old and sluggish, so still on old target frameworks. If this builds with that framework, could we add it? [ I'll send a PR if/when I remember :) ]

**Comment by jrouaix** [comment]
yes, will do, if you don't PR earlier.

**Comment by jrouaix** [comment]
next release will do : https://github.com/opentracing-contrib/csharp-decorators/commit/79819c1d5b54bcab3c2717e147e650e443c87d6b
