### ISSUE TITLE
Add basic hooks for implementors

### ISSUE THREAD

**Issue by ndrwrbgs** [opentracing-contrib/csharp-decorators#2]
https://github.com/opentracing-contrib/csharp-decorators/blob/41068bd2a764bf7ec80a6d181b3bdd8fd5eb5b1f/test/OpenTracing.Contrib.Decorators.Tests/DecoratorsTest.cs#L55-L67

As seen from the tests, it's going to be fairly common for some patterns to be observed in the wild. Would it be useful to expose a type of Base class that exposes these hooks directly, in addition to the bare-bones decorators that expose the OpenTracing interfaces? E.g. for TracerDecorator we'd allow the user to implement an OnScopeStarted and we'd handle the OpenTracing semantics for what possible ways there are to get to that state.

Obviously, feel free to 'no' this, since with the library as-is there's no reason a consumer/separate library couldn't implement this easily enough - I'm just musing over what we expose to the users.

**Comment by jrouaix** [comment]
I agree @ndrwrbgs, perhaps I can add some virtual OnSomething() methods in the decorators base.
Perhaps also I can provide some more building methods in the main builder. 
It was in a corner of my head but I didn't yet played enough with this library to see how to improve it the right way.

**Comment by jrouaix** [comment]
This will be the only way in vNext
