### ISSUE TITLE
[Feature] Consider passing the `_tagsApplies` to the SpanStarted method

### ISSUE THREAD

**Issue by ndrwrbgs** [opentracing-contrib/csharp-decorators#9]
I have **not** fully fleshed out this idea _(better for gitter or something, but this is the medium I have :smile: )_, but I have a use case where I am tempted to track these myself and it may be nice to have them passed to me.

I am implementing a simple sink for these traces, and most traces get their important tags at Builder time (I'm okay making that a requirement in my case). I would like to log those important tags along with the 'starting this span' information at one time. The alternative today is that I would have to capture OnSetSpanTags, cache them, and then use them at the OnStart call.

### Pros
* Can easily see the factory-time tags
* No need to worry about the lack of 'back-reference' from my cache to the objects it's holding data for (e.g. what if someone calls setTags and not start and lets GC collect their object, my cache would be a memory leak)
### Cons
* Perhaps a user SHOULDN'T be distinguishing between the factory tags and ones called later
* Backwards compat concerns
* It's a change, changes inherently require work and add risk

Thoughts on alternatives...
I could potentially use the baggage of the Span.Context to set such things
The library could use a non-generic ISpan in the delegates, that tracks the tags/logs it's been given (though since not everyone would want that memory overhead, it should be configurable or just provide the MEANS to track that info -- which is essentially just using baggage sans-propagation)

I'd be okay making the change if we think it's a change we want to take at all. Hoping @jrouaix and future- @ndrwrbgs can take a look at this proposal -- Thanks!

**Comment by jrouaix** [comment]
Hi @ndrwrbgs, do you have some code sample of the target API you'd like ?
If you could add to this issue, to help us think about it ?

**Comment by ndrwrbgs** [comment]
Issue was abandoned, so closing on myself ;)
